version: '3.4'

services:
  ditto_bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: registry.skyser.kr/shipduck/ditto_bot
    environment:
      - token=$token
      - REDIS_HOST=redis
    deploy:
      placement:
        constraints:
          - node.hostname == jetson
