kind: pipeline
type: docker
name: ditto

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: plugins/docker
  settings:
    registry: registry.skyser.kr
    repo: registry.skyser.kr/shipduck/ditto_bot
    dockerfile: /drone/src/docker/Dockerfile
    config:
      from_secret: docker_auth_config

- name: publish
  image: alpine
  command:
  - sh
  - -c
  - apk add --update curl && curl -X POST $portainer_webhook
  environment:
   portainer_webhook:
     from_secret: portainer_webhook
  when:
    branch:
    - master
    event:
    - push
